### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by EmmaSweeney** [kingrpaul/eleanor-h-porter_pollyanna-grows-up#2]
- [x] Please run `se clean .`

For the short description:
- [x] Reword this section.
(This, the second of the Pollyanna books, follows..) --> (The second Pollyanna book follows...)

- [x] Reword this section. (...the interconnectedness of the human family.)

For the long description:
- [x] Reword the dependent clause.
(In this, the second of the Pollyanna “Glad” books, we...) --> (In the Pollyanna “Glad” books, we...)

- [x] Remove "...that crippled her at the close of the first book."

- [x] Add "been" before "rehabilitated" (...having just rehabilitated from the...)

- [x] Reword the last two sentences in the first paragraph. 
(When Pollyanna departs Boston, she also leaves the country, and leaves the story for a time. She does not return until age 20 with her Aunt Polly, who is now widowed and faced with insolvency.) --> (Pollyanna leaves the country with her Aunt Polly and doesn't return to Boston until she is 20 years old.)

- [x] Reword the first sentence in the second paragraph. (While still in Boston, Pollyanna had observed her host’s spiritual poverty, which sat in stark contrast with the opulence of her home and her material wealth.)

- [x] Change a semicolon to a comma. (...Meanwhile; naïve...)

- [x] Change "positively" to "positive." (...relentlessly positivity, literal-minded...)

- [x] Add a hyphen in between "of" and "the." (...turn-of the-century...)

- [x] Rework the first two sentences in the third pargraph. (In the second half of the story, Pollyanna acts as host to the Boston friends she made in the first half; reconnecting with them and connecting them with her Vermont friends and family from the first book. In the process of growing up, Pollyanna must now engage with questions of how these relationships might change as her age and social status have changed, and must reconcile the sense of obligation she feels with her own desires, and with the wants and needs of those around her.)

- [x] Replace "in" with "with." (...concludes in a fairy-tale ending...)

- [x] Reword this section.
(...with the multifaceted romantic awkwardness, which has developed across the book, being resolved) --> (... of a multifaceted romance.)

- [x] Add "are" before "formed." (...new relationships formed (or revealed)...)

- [x] Add a comma before "and." (...are expanded and new relationships...)

**Comment by kingrpaul** [comment]
Made more brief.
