### ISSUE TITLE
Long description Issues

### ISSUE THREAD

**Issue by EmmaSweeney** [kingrpaul/eleanor-h-porter_pollyanna-grows-up#3]
- [x]  "In the second half of the book, Pollyanna acts as host to the Boston friends she made in the book’s first half."
You refer to both "the second half of the book" and the "book’s first half" in a single sentence. Please reword this sentence.

- [x]  "And, she must reconcile the sense of obligation she feels with her desires, and with the wants and needs of those around her."
Remove the first "and" and the following comma. Capitalize "she." 

- [x] . "And, she must reconcile the sense of obligation she feels with her own desires, and with the wants and needs of those around her."
Please remove "own." It is redundant.

- [x]  "The story concludes with a fairy-tale ending, in which a multifaceted romantic awkwardness, which has developed across the book, is resolved."
This sentence has grammatical issues. Please reword this sentence.

- [x]  "After leaving Boston, Pollyanna leaves the country with her Aunt Polly and doesn’t return to Boston until she is 20 years old."
You mention her leaving and Boston twice in the sentence. Remove "after leaving Boston." This will take care of the repetitions.

- [x]  Can you be a little more specific on how "old relationships are expanded"?

**Comment by kingrpaul** [comment]
1. OK 
2. I've done as you asked, though I do not agree.
3. I've done as you asked, though I do not agree.
4. Truncated
5. Corrected incorrect word. 
6. Not without revealing more than I think is the right amount. I'd prefer not to remove the sentence.
